### ISSUE TITLE
readme typo's

### ISSUE THREAD

**Issue by joecombopiano** [OfficeDev/skype-web-sdk-simple-sample-for-SfB-online#1]
Was looking through the example code - nice work! I noticed a few typos in the readme. I created a branch that addresses these, let me know if you'd like me to push this to the origin for review.

**Comment by masa-fleet** [comment]
Hi @joecombopiano , thanks for publishing new issue and making your branch! Would you please push it for review?

In Microsoft repository, we should follow Contribute License Agreement, so please check [the site](https://cla.microsoft.com/) and fill out the form before pushing.

thanks,
masa

**Comment by masa-fleet** [comment]
hi @joecombopiano how is it? I'm looking forward to see your branch :)

**Comment by masa-fleet** [comment]
I'll close this issue in next 7 days, if joe will not reply.

**Comment by joecombopiano** [comment]
hey @NT-D , sorry for the delayed response! I just submitted the CLA, and I will push my changes as soon as I can.

**Comment by masa-fleet** [comment]
Hey @joecombopiano , thanks for your reply and submit CLA. I'm looking forward to see your push :)
best,
masa

**Comment by masa-fleet** [comment]
Because I've not receive push for 1 month, I close this issue once. If you made branch and have a time to push, please make issue again and push it :)

Thanks,
masa
